IpfsHost = "http://0.0.0.0"
IpfsPort = "8080"
CompilersHost = "https://compilers.monax.io"
CompilersPort = "10120"
CrashReport = "bugsnag"
ImagesPullTimeout = "15m"
Verbose = false
DefaultRegistry = "quay.io"
ImageData = "eris/data:0.12.0"
ImageKeys = "eris/keys:0.12.0"
ImageDB = "eris/db:0.12.0"
ImagePM = "eris/pm:0.12.0"
ImageCM = "eris/cm:0.12.0"
ImageIPFS = "eris/ipfs"
ImageCompilers = "eris/compilers:0.12.0"
