# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "Root"

definition = """
Users who have a key which is registered with root privileges can do everything
on the chain. They have all of the permissions possible.
"""

typical_user = """
If you are making a small chain just to play around then usually you would
give all of the accounts needed for your experiment root privileges (unless you
were testing different) privilege types.

If you are making a more complex chain, then you would usually have a few
keys which have registered root permissions and as such will act in a capacity
similar to a network administrator in other data management situations.
"""

default_number = 3

default_tokens = 9999999999

default_bond = 0

[perms]
root = 1
send = 1
call = 1
create_contract = 1
create_account = 1
bond = 1
name = 1
has_base = 1
set_base = 1
unset_base = 1
set_global = 1
has_role = 1
add_role = 1
rm_role = 1
