# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "simplechain"

definition = """
A simple chain type will build a single node chain. This chain type is useful
for quick and easy prototyping. It should not be used for anything more than
the most simple prototyping as it only has one node and the keys to that node
could get lost or compromised and the chain would thereafter become useless.
"""

[account_types]
Full = 1
Developer = 0
Participant = 0
Root = 0
Validator = 0

[messenger]

[manager]

[consensus]

